module.exports = {
    alerts: require('./alerts'),
    aspectRatios: require('./aspect-ratios'),
    base: require('./base'),
    breadcrumb: require('./breadcrumb'),
    breakOut: require('./break-out'),
    buttons: require('./buttons'),
    columns: require('./columns'),
    groupVariants: require('./group-variants'),
    headings: require('./headings'),
    horizontalRule: require('./horizontal-rule'),
    icons: require('./icons'),
    images: require('./images'),
    lazyload: require('./lazyload'),
    links: require('./links'),
    loading: require('./loading'),
    position: require('./position'),
    richtext: require('./richtext'),
    social: require('./social'),
};
